### ISSUE TITLE
14px

### ISSUE THREAD

**Issue by tobia** [koemaeda/gohufont-ttf#1]
Thanks for tracing this font.
I'm trying to use the 14px version in a Qt program in Linux, where I cannot use the original bitmap GohuFont, but all I get is a scaled and blocky 11px version. I've tried both ttf files.
How do you trigger the 14px one?

**Comment by koemaeda** [comment]
Hi! This font was traced using the glyphs for the 11px one only. I'll retrace it using the 14px glyphs and update the project with the two versions.

**Comment by tobia** [comment]
Thank you, that would be great.
I thought there was the 14px inside somehow, because it was mentioned in the Readme. But I realize it's probably the original font's Readme.

**Comment by koemaeda** [comment]
I've separated the TTF fonts traced from the 11px and 14px original fonts, just uploaded them:
- gohufont-11.ttf
- gohufont-uni-11.ttf
- gohufont-14.ttf
- gohufont-uni-14.ttf

**Comment by tobia** [comment]
Awesome, thank you!
